# Generated by Django 4.2.11 on 2024-03-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.CharField(help_text='輸入姓名', max_length=60),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='price',
            field=models.IntegerField(help_text='金額'),
        ),
    ]
