# Generated by Django 4.2.11 on 2024-03-27 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_coffee_name_alter_coffee_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffee',
            options={'ordering': ['name', 'price']},
        ),
    ]
